[package]
authors = ["Vincent Esche <regexident@gmail.com>"]
categories = [
    "no-std",
    "embedded",
    "multimedia",
    "science",
    "algorithms",
]
description = "A collection of traits used in 'signalo' umbrella crate."
documentation = "https://docs.rs/svm"
keywords = [
    "dsp",
    "digital-signal",
    "signal-processing",
    "filters",
    "pipeline",
]
license = "MPL-2.0"
name = "signalo_traits"
readme = "README.md"
repository = "https://github.com/signalo/signalo"
homepage = "https://github.com/signalo/signalo/tree/master/traits"
version = "0.2.1"

[dependencies.missing_mpl]
version = "~0.1"
optional = true

[features]
default = ["std"]
std = []
nightly = ["missing_mpl"]
